language: android
jdk: oraclejdk7

branches:
    only:
        - master
        - testing

before_script:
    - wget http://services.gradle.org/distributions/gradle-2.1-bin.zip
    - unzip gradle-2.1-bin.zip
    - export GRADLE_HOME=$PWD/gradle-2.1
    - export PATH=$GRADLE_HOME/bin:$PATH
    - echo yes | android update sdk --filter extra-android-support --no-ui --force > /dev/null
    - echo yes | android update sdk --filter extra-android-m2repository --no-ui --force > /dev/null

android:
    components:
        - platform-tools
        - tools
        - android-L
        - extra

script: "gradle assemble --stacktrace --debug"
