language: android

before-install:
    - wget http://services.gradle.org/distributions/gradle-2.1-bin.zip
    - unzip gradle-2.1-bin.zip
    - export GRADLE_HOME=$PWD/gradle-2.1
    - export PATH=$GRADLE_HOME/bin:$PATH

android:
    components:
        - platform-tools
        - tools
        - android-20
        - extra

script: "gradle assemble"
